//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontrlWork.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Order { get; set; }
        public int Id_client { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Id_employee { get; set; }
        public bool Accepted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
