//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontrlWork.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int Id_OrderServise { get; set; }
        public int Id_service { get; set; }
        public int Id_order { get; set; }
    }
}
